# set shell to zsh
export SHELL=/bin/zsh

export ZSH='/home/donnachaheff/.oh-my-zsh'
export CONFIG_HOME=$HOME/.config

export ZSH_PLUGIN_MANAGER='antigen'

source $CONFIG_HOME/antigen/antigen.zsh
source $ZSH/oh-my-zsh.sh

antigen use oh-my-zsh

# syntax highlights
antigen bundle 'zsh-users/zsh-syntax-highlighting'
# get autosuggestions as I type
antigen bundle 'zsh-users/zsh-autosuggestions'
# jump quick to directories frequently visited by writing shorthand
antigen bundle 'agkozak/zsh-z'

# antigen bundle 'zsh-users/zsh-completions'

# theme
antigen theme denysdovhan/spaceship-prompt

antigen apply


ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=6'

# fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh



